### ISSUE TITLE
Where Contributor.md?

### ISSUE THREAD

**Issue by pratikbutani** [dsckiet/hacktoberfest-first-pr#22]
Where is Contributor.md? I found only ReadMe.md

**Comment by rhnmht30** [comment]
@pratikbutani I guess you are the first one here! yay! 
Make one.

**Comment by pratikbutani** [comment]
> @pratikbutani I guess you are the first one here! yay!
> Make one.

I have [created](https://github.com/dsckiet/hacktoberfest-first-pr/pull/25) and sent PR.

**Comment by rhnmht30** [comment]
Merged #23 Congrats :rocket:

**Comment by pratikbutani** [comment]
Thank you so much :)
